/**
 * Generated, unique identifier for users. Currently generated by Firestore
 * auth.
 * TODO: ideally, we shouldn't just rely on a Firestore Auth proprietary thing
 * for these ids, just use Id below.
 */
export type Uid = string;

/**
 * Unique identifier derived from user name
 */
export type Mid = string;

/**
 * Generated, general id for everything but users.
 * TODO: ideally we should just use these, instead of Uids
 */
export type Id = string;
